spring:
  datasource:
    url: jdbc:mysql://localhost:3306/sweet_peach?useSSL=false
    username: root

  mail:
      host: live.smtp.mailtrap.io
      port: 587
      username: api
      password: de8d52b743ba031d75edc6ef723a48e2
      properties:
        mail:
          smtp:
            auth: true
            starttls:
              enable: true

server:

   port: 8080
jwt:
  secret: mySecretKey
  expiration: 2592000000

